[package]
name = "caat_rust"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
dirs-next = "2.0.0"
interprocess = "1.2.1"
